version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    # volumes:
    #   - ./:/usr/src/app
#     # env_file:
#     #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=GOOGLE4LYF
      - DATABASE_NAME=19hrs - Tutorial
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
#     command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#     depends_on:
#       - postgres

  postgres:
    image: postgres #:13
    # expose:
    #   - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=GOOGLE4LYF
      - POSTGRES_DB=19hrs - Tutorial
    volumes:
      - postgres-db:/var/lib/postgresql/data/
#     ports:
#       - "5432:5432"

volumes:
  postgres-db:






# version: '3.8'

# services:
#   api:
#     build: .
#     command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
#     volumes:
#       - .:/app
#     ports:
#       - 8008:8000
#     environment:
#       - DATABASE_URL=postgresql://postgres:GOOGLE4LYF@postgres:5432/19hrs - Tutorial
#     depends_on:
#       - db
#   db:
#     image: postgres:13-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     expose:
#       - 5432
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=GOOGLE4LYF
#       - POSTGRES_DB=19hrs - Tutorial

# volumes:
#   postgres_data: