name: Build and Delopy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v3
      - name: Say hi to Kweku
        run: echo "Hellow Kweku"
        